// Room statuses
export const ROOM_STATUS = Object.freeze({
  WAITING: 'WAITING',
  READY: 'READY',
  STARTING: 'STARTING',
  PLAYING: 'PLAYING',
  PAUSED: 'PAUSED',
  FINISHED: 'FINISHED',
  CLOSED: 'CLOSED',
});

// Room config defaults
export const ROOM_DEFAULTS = Object.freeze({
  CODE_LENGTH: 6,
  CODE_CHARS: 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789',
  MAX_PLAYERS: 8,
  MIN_PLAYERS: 2,
  RECONNECT_TIMEOUT_MS: 30_000,
  IDLE_TIMEOUT_MS: 300_000,
  COUNTDOWN_SECONDS: 3,
});
